name: Validando rota de usuários

on:
  workflow_dispatch:

  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{secrets.BASE_URL}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install newman
        run: npm install -g newman

      - name: Install Newman-Reporter-HtmlExtra
        run: npm install -g newman-reporter-htmlextra

      - name: Executando as collections do postman via terminal
        run: newman run postman_collection.json --globals postman_environment.json
        
      - name: Gerando relatório das execuções das collections do postman
        run: newman run postman_collection.json -e postman_environment.json --reporters html,cli --reporter-html-export newman_report.html

      - name: Upload Newman report as artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: report-newman
          path: newman_report.html

      - name: Instalar dependencias
        run: npm install

      - name: Executar os testes
        run: npm run test


